name = "ldc-shop-v2"
main = "worker.js"
compatibility_date = "2026-01-06"
 
# Custom Domain (Optional)
# If you want to use a custom domain, uncomment the lines below and replace "shop.example.com" with your own domain (e.g., "store.yourdomain.com").
# If you don't need a custom domain (using *.workers.dev), keep these lines commented out.
# routes = [
# 	{ pattern = "shop.example.com", custom_domain = true }
# ]
 
# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ldc-shop-db"
database_id = "aaa6fa50-0b95-4684-8a5a-b643c80aba8e"
# preview_database_id = "DB" # Use strictly for local dev

[triggers]
crons = ["*/1 * * * *"]
